### ISSUE TITLE
New version failed on SQLite

### ISSUE THREAD

**Issue by ziorufus** [tatuylonen/wikitextprocessor#139]
When I try the example code (in the README) using the last version, `pip`-installed from local after a `git clone`, I get:

```
Traceback (most recent call last):
  File "/path/to/template.py", line 13, in <module>
    process_dump(
  File "/path/to/env/lib/python3.10/site-packages/wikitextprocessor/dumpparser.py", line 132, in process_dump
    analyze_and_overwrite_pages(
  File "/path/to/env/lib/python3.10/site-packages/wikitextprocessor/dumpparser.py", line 158, in analyze_and_overwrite_pages
    ctx.analyze_templates()
  File "/path/to/env/lib/python3.10/site-packages/wikitextprocessor/core.py", line 1043, in analyze_templates
    self.db_conn.execute(query_str)
sqlite3.OperationalError: near "FROM": syntax error
```

How can I solve it?

**Comment by xxyzz** [comment]
[`update from`](https://www.sqlite.org/lang_update.html#upfrom) is supported since 3.33.0, you need to update sqlite or Python.

**Comment by ziorufus** [comment]
These are the versions of my packages. Is it possible that the SQLite version inside Python is different from the one used from the shell?

```
$ sqlite3 --version
3.33.0 2020-08-14 13:23:32 fca8dc8b578f215a969cd899336378966156154710873e68b3d9ac5881b0alt2
$ python --version
Python 3.10.13
```

**Comment by ziorufus** [comment]
Also tried to update SQLite to 3.34.1.

```
$ python extract.py 
Traceback (most recent call last):
  File "/path/to/extract.py", line 13, in <module>
    process_dump(
  File "/path/to/env/lib/python3.10/site-packages/wikitextprocessor/dumpparser.py", line 132, in process_dump
    analyze_and_overwrite_pages(
  File "/path/to/env/lib/python3.10/site-packages/wikitextprocessor/dumpparser.py", line 158, in analyze_and_overwrite_pages
    ctx.analyze_templates()
  File "/path/to/env/lib/python3.10/site-packages/wikitextprocessor/core.py", line 1043, in analyze_templates
    self.db_conn.execute(query_str)
sqlite3.OperationalError: near "FROM": syntax error

$ sqlite3 --version
3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ebd1f
```

Is it possible that I need to update SQLite in the Python env?
