### ISSUE TITLE
Module 'ne-conj' not found Lua error

### ISSUE THREAD

**Issue by xxyzz** [tatuylonen/wikitextprocessor#172]
Page: https://en.wiktionary.org/wiki/वाक्नु
Error: https://kaikki.org/dictionary/errors/details-Traceback--most-recent-call-last-----F-Plr1Wuzg.html

```
वाक्नु (Nepali verb) LUA error in #invoke('ne-conj', 'show') parent ('Template:ne-conj', {'i': 'y'})

Traceback (most recent call last):
  File "/home/ubuntu/temp-wiktionary/venv/lib/python3.10/site-packages/wikitextprocessor/luaexec.py", line 745, in call_lua_sandbox
    ret: tuple[bool, str] = ctx.lua_invoke(
  File "lupa/lua51.pyx", line 896, in lupa.lua51._LuaObject.__call__
  File "lupa/lua51.pyx", line 1795, in lupa.lua51.call_lua
  File "lupa/lua51.pyx", line 1821, in lupa.lua51.execute_lua_call
  File "lupa/lua51.pyx", line 1703, in lupa.lua51.raise_lua_error
lupa.lua51.LuaError: [string "_sandbox_phase2"]:179: Could not find module ne-conj: module 'ne-conj' not found
stack traceback:
	[string "_sandbox_phase2"]:179: in function <[string "_sandbox_phase2"]:121>
	[C]: in function 'error'
```

Unreproducible error, have no idea.

**Comment by kristian-clausal** [comment]
Yeah, I bet this won't show up again... I don't think we can do much about these kinds of errors. I'll ask Tatu if he wants to continue hunting for the "LAMBDA" bugs still, but now that you implemented lua invocation isolation it's not as pressing anymore.

I think we might just have to live with random weird memory errors, now that they are isolated and have a smaller impact like this (if this is the same kind of issue, of course). If there is need, we can just run things twice (or thrice) and join together the good parts of the runs into one and discard "bad" parts with errors.

**Comment by xxyzz** [comment]
This exact error happens before and I suspect it might be a wrong cache page from another namespace: https://github.com/tatuylonen/wikitextprocessor/commit/c151d393c1fc343c195d6fe64c6470d94b81df8c

but that doesn't work...

**Comment by xxyzz** [comment]
I haven't seen this kind of error for a long time, maybe it's already fixed and the issue could be closed.
