### ISSUE TITLE
Filenames cause errors on exFAT

### ISSUE THREAD

**Issue by brendanedwardgavin** [tatuylonen/wikitextprocessor#63]
exFAT partitions disallow file names with the characters `/\:*?\"<>|` and unicode 0x00-0x1F; some wiktionary titles violate this rule, causing the following error when extracting the wiktionary raw dump:
```
2023-06-20 13:26:17,038 INFO:   ... 8420000 raw pages collected
Getting all pages for query: 'SELECT title, namespace_id, redirect_to, need_pre_expand, body, model FROM pages ORDER BY title ASC'
Traceback (most recent call last):
  File "/home/brendan/miniconda3/envs/wiktextract/bin/wiktwords", line 8, in <module>
    sys.exit(main())
  File "/home/brendan/miniconda3/envs/wiktextract/lib/python3.10/site-packages/wiktextract/wiktwords.py", line 331, in main
    parse_wiktionary(wxr, args.path, word_cb,
  File "/home/brendan/miniconda3/envs/wiktextract/lib/python3.10/site-packages/wiktextract/wiktionary.py", line 94, in parse_wiktionary
    for _ in wxr.wtp.process(
  File "/home/brendan/miniconda3/envs/wiktextract/lib/python3.10/site-packages/wikitextprocessor/core.py", line 1513, in process
    process_dump(
  File "/home/brendan/miniconda3/envs/wiktextract/lib/python3.10/site-packages/wikitextprocessor/dumpparser.py", line 120, in process_dump
    save_pages_to_file(ctx, save_pages_path)
  File "/home/brendan/miniconda3/envs/wiktextract/lib/python3.10/site-packages/wikitextprocessor/dumpparser.py", line 201, in save_pages_to_file
    file_path.parent.mkdir(parents=True, exist_ok=True)
  File "/home/brendan/miniconda3/envs/wiktextract/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 22] Invalid argument: '../wiktextract-dump-2023-06-20/Words/!?'
```

**Comment by kristian-clausal** [comment]
I get where you're coming from, but the raw text pages that are extracted at that stage are basically debug pages. They're a handy way for people to access the original wikitext if need be, copying files for modification and testing, and finally as a way to pin-point a specific page when parsing a single page with `--page`. They should be, as much as possible, easily accessible when manually writing out the file-path, but not critical for end-users. Yunpeng has also recently changed --page to also just accept article titles that are searched for in the new database file.

That out of the way, exFAT-safe file names are fine as a command-line option like `--exfat-safe`, so I'll ok the pull request if you can add that.

**Comment by xxyzz** [comment]
I'm kind of curious why you choose to use exFAT on Linux. It doesn't have journal like most other file systems. Maybe you need to share the disk with a dual boot Windows?

**Comment by brendanedwardgavin** [comment]
@xxyzz yes that's exactly it; I wanted to be able to access this partition from a Windows install too. 

@kristian-clausal yeah I didn't figure out that it was only for debugging purposes until after I made the changes, so I figured that I might as well commit it in case it helps anyone else to avoid going down the same rabbit hole.

I agree it's not very important, so I'd rather not clutter non-debug function interfaces with extra flags for this purpose (which I think I'd need to do in order to add a command line argument). 

What do you think about checking for the filesystem type, and only replacing Windows-invalid characters when it's exFAT or NTFS? I made changes to do that so you can see what it looks like. If that seems good then feel free to merge it, otherwise let's drop it.

**Comment by kristian-clausal** [comment]
Merged pull-request, closed as complete.
